---
title: "04_application"
author: "Raven McKnight"
date: "1/16/2020"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Case Study

## Background

Metro Transit is the primary transit provider in the Minneapolis-Saint Paul metropolitan area. The agency is interested in predicting transit demand across the region in order to guide route planning and service provision. Currently, Metro Transit uses a set of 5 Transit Market Areas to estimate spatial demand. The Transit Market Areas are writen into the official Transportation Planning Policy (TPP) and are calculated using a simple linear regression. Following the notation of the TPP, the formula for determing Transit Market Areas is expressed

\begin{align}
\text{Transit Market Index }  = & 0.64\text{ * population density} + 0.23\text{ * intersection density} +  \\
& 0.20\text{ * employment_density} + 0.11\text{ * automobile availability}
\end{align}

where each predictor is logged and scaled by developed land acreage per census block group. Here, automobile availability refers to the number of adults over age 16 less the total number of automobiles available in a block group (scaled by developed land acreage). There is an additional indicator variable, omitted in this notation, for the census block group containing the MSP International Airport. For more documentation of the official Transit Market Areas, refere to the TPPs [Appendix G](https://metrocouncil.org/Transportation/Planning-2/Key-Transportation-Planning-Documents/Transportation-Policy-Plan/The-Adopted-2040-TPP-(1)/Final-2040-Transportation-Policy-Plan/2040-TPP-Appendix-G-Transit-Design-and-Perf-Standa.aspx). 

Census block groups are split into 5 market areas based on the Transit Market Index described above, where the highest market area (Market Area 1) is expected to support high-frequency, all-day service and the lowest market area (Market Area 5) is expected to support peak commuter express service, if that. 

The Transit Market Index values are geographically smoothed to create more-or-less concentric Transit Market Areas. 

## Data Description

## Data Preperation

## Modeling

### Poisson Regression

### Horseshoe Prior

### Overdispersion

### Spatial Structure